version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: baykar
      POSTGRES_PASSWORD: Baykar.iha
      POSTGRES_DB: baykar_iha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network
    ports:
      - "5433:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django_network

networks:
  django_network:

volumes:
  postgres_data:
