# Generated by Django 4.2 on 2024-11-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('assembled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('units_in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProducedPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('airplane', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventories.airplane')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.piece')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='airplane',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='airplanes', to='inventories.producedpiece'),
        ),
    ]
