# Generated by Django 4.2 on 2024-11-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_rename_model_airplane_name_remove_airplane_assembled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producedpiece',
            name='airplane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produced_pieces', to='inventories.airplane'),
        ),
    ]
