# Generated by Django 4.2 on 2024-11-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_alter_producedpiece_airplane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producedpiece',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.airplane'),
        ),
    ]
