# Generated by Django 4.2 on 2024-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_producedpiece_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producedairplane',
            name='parts',
            field=models.ManyToManyField(blank=True, to='inventories.producedpiece'),
        ),
    ]
